//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BONUS_SALARY_BASEUP
    {
        public string COMPANY_CD { get; set; }
        public int ASSESSMENT_YEAR { get; set; }
        public decimal COUNTRY_EXPECTED_RATIO { get; set; }
        public decimal BASEUP_RATE { get; set; }
        public Nullable<decimal> GAP_RATE { get; set; }
        public string COMMENT { get; set; }
        public decimal BAND_I_VARIATION { get; set; }
        public decimal BAND_IIC_VARIATION { get; set; }
        public decimal BAND_IIB_VARIATION { get; set; }
        public decimal BAND_IIA_VARIATION { get; set; }
        public decimal BAND_IIIC_VARIATION { get; set; }
        public decimal BAND_IIIB_VARIATION { get; set; }
        public decimal BAND_IIIA_VARIATION { get; set; }
        public decimal BAND_IV_VARIATION { get; set; }
        public decimal BAND_I_FINALRATIO { get; set; }
        public decimal BAND_IIC_FINALRATIO { get; set; }
        public decimal BAND_IIB_FINALRATIO { get; set; }
        public decimal BAND_IIA_FINALRATIO { get; set; }
        public decimal BAND_IIIC_FINALRATIO { get; set; }
        public decimal BAND_IIIB_FINALRATIO { get; set; }
        public decimal BAND_IIIA_FINALRATIO { get; set; }
        public decimal BAND_IV_FINALRATIO { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    }
}
