//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_STAFF()
        {
            this.M_PERSON = new HashSet<M_PERSON>();
            this.T_STAFF_EDUCATION = new HashSet<T_STAFF_EDUCATION>();
            this.T_STAFF_EMPLOYMENT_HISTORY = new HashSet<T_STAFF_EMPLOYMENT_HISTORY>();
        }
    
        public string COMPANY_CD { get; set; }
        public int STAFF_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string NICKNAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> JOINED_DATE { get; set; }
        public string STAFF_CATEGORY { get; set; }
        public string GROUP_CD { get; set; }
        public string DIVISION_CD { get; set; }
        public string SECTION_CD { get; set; }
        public Nullable<int> JOBTITLE_CD { get; set; }
        public string PHOTOID_URL { get; set; }
        public string HOME_TOWN { get; set; }
        public Nullable<System.DateTime> PHOTOID_UPLOAD_DATE { get; set; }
        public string INSTRUCTOR_ID { get; set; }
        public Nullable<System.DateTime> RESIGNATION_DATE { get; set; }
        public string RESIGNATION_REASON { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    
        public virtual M_DIVISION M_DIVISION { get; set; }
        public virtual M_GROUP M_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PERSON> M_PERSON { get; set; }
        public virtual M_SECTION M_SECTION { get; set; }
        public virtual M_STAFF_BAND_SALARY M_STAFF_BAND_SALARY { get; set; }
        public virtual M_STAFF_JOBTITLE M_STAFF_JOBTITLE { get; set; }
        public virtual T_STAFF_CONTACT T_STAFF_CONTACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_STAFF_EDUCATION> T_STAFF_EDUCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_STAFF_EMPLOYMENT_HISTORY> T_STAFF_EMPLOYMENT_HISTORY { get; set; }
    }
}
