//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_STAFF_BAND_SALARY
    {
        public string COMPANY_CD { get; set; }
        public int STAFF_ID { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string STAFF_BAND { get; set; }
        public Nullable<decimal> BASIC_SALARY { get; set; }
        public Nullable<decimal> ALLOWANCE { get; set; }
        public Nullable<decimal> BONUS { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    
        public virtual M_STAFF M_STAFF { get; set; }
    }
}
