//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_STAFF_JOBTITLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_STAFF_JOBTITLE()
        {
            this.M_STAFF = new HashSet<M_STAFF>();
        }
    
        public string COMPANY_CD { get; set; }
        public int JOBTITLE_CD { get; set; }
        public string JOBTITLE_NAME { get; set; }
        public string JOBTITLE_DESC { get; set; }
        public bool PRESIDENT_FLG { get; set; }
        public bool GM_FLG { get; set; }
        public bool DEPUTY_GM_FLG { get; set; }
        public bool GROUP_LEADER_FLG { get; set; }
        public bool DIV_LEADER_FLG { get; set; }
        public bool SEC_LEADER_FLG { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_STAFF> M_STAFF { get; set; }
    }
}
