//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG_SUBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSG_SUBJECT()
        {
            this.MSG_MESSAGE = new HashSet<MSG_MESSAGE>();
            this.MSG_SUBJECT_PARTICIPANT = new HashSet<MSG_SUBJECT_PARTICIPANT>();
        }
    
        public string SUBJECT_ID { get; set; }
        public string SUBJECT { get; set; }
        public Nullable<byte> IS_PRIVATE_MESSAGE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_USER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSG_MESSAGE> MSG_MESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSG_SUBJECT_PARTICIPANT> MSG_SUBJECT_PARTICIPANT { get; set; }
    }
}
