//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG_MESSAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSG_MESSAGE()
        {
            this.MSG_ATTACHMENT = new HashSet<MSG_ATTACHMENT>();
            this.MSG_MESAGES_USERS = new HashSet<MSG_MESAGES_USERS>();
        }
    
        public decimal MESSAGE_ID { get; set; }
        public string SUBJECT_ID { get; set; }
        public string CONTENTS { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public Nullable<int> SENDING_USER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSG_ATTACHMENT> MSG_ATTACHMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSG_MESAGES_USERS> MSG_MESAGES_USERS { get; set; }
        public virtual MSG_SUBJECT MSG_SUBJECT { get; set; }
    }
}
