//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG_USERS_CONTACTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSG_USERS_CONTACTS()
        {
            this.MSG_USERS_IN_GROUPS = new HashSet<MSG_USERS_IN_GROUPS>();
        }
    
        public int USER_ID { get; set; }
        public int FRIEND_ID { get; set; }
        public Nullable<System.DateTime> TOBE_FRIEND_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSG_USERS_IN_GROUPS> MSG_USERS_IN_GROUPS { get; set; }
    }
}
