//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LOG
    {
        public string LOG_CD { get; set; }
        public string LOG_TYPE { get; set; }
        public string SCREEN_NAME { get; set; }
        public string ACTION_TYPE { get; set; }
        public string LOG_DATA { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<int> PERSON_CD { get; set; }
    }
}
