//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EXTENSION_ATTRIBUTE
    {
        public string ATTRIBUTE_CD { get; set; }
        public string PRODUCT_CD { get; set; }
        public string ATTRIBUTE_KEY { get; set; }
        public string ATRRIBUTE_VALUE { get; set; }
    
        public virtual V_PRODUCT V_PRODUCT { get; set; }
    }
}
