//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.Commons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vap.Properties.CommonMessages", typeof(CommonMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files have been successfully uploaded..
        /// </summary>
        public static string Common_Msg_AllFilesUploadSuccess {
            get {
                return ResourceManager.GetString("Common_Msg_AllFilesUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one item to delete..
        /// </summary>
        public static string Common_Msg_ChooseToDelete {
            get {
                return ResourceManager.GetString("Common_Msg_ChooseToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one item to update..
        /// </summary>
        public static string Common_Msg_ChooseToUpdate {
            get {
                return ResourceManager.GetString("Common_Msg_ChooseToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be the greater or the equals than {1}..
        /// </summary>
        public static string Common_Msg_CompareTwoYear {
            get {
                return ResourceManager.GetString("Common_Msg_CompareTwoYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion this record?.
        /// </summary>
        public static string Common_Msg_DeleteConfirm {
            get {
                return ResourceManager.GetString("Common_Msg_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has not been successfully deleted. Please recheck all the data..
        /// </summary>
        public static string Common_Msg_DeleteFail {
            get {
                return ResourceManager.GetString("Common_Msg_DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been successfully deleted..
        /// </summary>
        public static string Common_Msg_DeleteSuccess {
            get {
                return ResourceManager.GetString("Common_Msg_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has not been successfully exported to excel file..
        /// </summary>
        public static string Common_Msg_ExcelExportFail {
            get {
                return ResourceManager.GetString("Common_Msg_ExcelExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been successfully exported to excel file..
        /// </summary>
        public static string Common_Msg_ExcelExportSuccess {
            get {
                return ResourceManager.GetString("Common_Msg_ExcelExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string Common_Msg_Exception {
            get {
                return ResourceManager.GetString("Common_Msg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected files do not belong to {0} company..
        /// </summary>
        public static string Common_Msg_FileDoesNotBelongToCurrentCompany {
            get {
                return ResourceManager.GetString("Common_Msg_FileDoesNotBelongToCurrentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected files do not belong to this function..
        /// </summary>
        public static string Common_Msg_FileDoNotBelongToFunction {
            get {
                return ResourceManager.GetString("Common_Msg_FileDoNotBelongToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been successfully uploaded..
        /// </summary>
        public static string Common_Msg_FileUploadSuccess {
            get {
                return ResourceManager.GetString("Common_Msg_FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path name is not exist..
        /// </summary>
        public static string Common_Msg_FullPathFileNameNotExist {
            get {
                return ResourceManager.GetString("Common_Msg_FullPathFileNameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not inserted successfully. Please recheck all the data..
        /// </summary>
        public static string Common_Msg_InsertFail {
            get {
                return ResourceManager.GetString("Common_Msg_InsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been successfully inserted..
        /// </summary>
        public static string Common_Msg_InsertSuccess {
            get {
                return ResourceManager.GetString("Common_Msg_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. System only support .xls or .xlsx format. Please try again..
        /// </summary>
        public static string Common_Msg_InvalidExcelFileType {
            get {
                return ResourceManager.GetString("Common_Msg_InvalidExcelFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value..
        /// </summary>
        public static string Common_Msg_InvalidFormat {
            get {
                return ResourceManager.GetString("Common_Msg_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of image file is invalid.
        /// </summary>
        public static string Common_Msg_InvalidImageFileFullPath {
            get {
                return ResourceManager.GetString("Common_Msg_InvalidImageFileFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image type is invalid, supported types are .bmp, .jpg, .png and .jpeg..
        /// </summary>
        public static string Common_Msg_InvalidImageFileType {
            get {
                return ResourceManager.GetString("Common_Msg_InvalidImageFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter numeric value..
        /// </summary>
        public static string Common_Msg_InvalidNumeric {
            get {
                return ResourceManager.GetString("Common_Msg_InvalidNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid year..
        /// </summary>
        public static string Common_Msg_InvalidYear {
            get {
                return ResourceManager.GetString("Common_Msg_InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in mandatory fields..
        /// </summary>
        public static string Common_Msg_ManatoryFields {
            get {
                return ResourceManager.GetString("Common_Msg_ManatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill at least one condition..
        /// </summary>
        public static string Common_Msg_NoAnyConditionToSearch {
            get {
                return ResourceManager.GetString("Common_Msg_NoAnyConditionToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        public static string Common_Msg_NoRecordsFound {
            get {
                return ResourceManager.GetString("Common_Msg_NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect, please input again..
        /// </summary>
        public static string Common_Msg_PasswordIncorrect {
            get {
                return ResourceManager.GetString("Common_Msg_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session timeout occurred or the login process was skipped..
        /// </summary>
        public static string Common_Msg_RequestTimeOut {
            get {
                return ResourceManager.GetString("Common_Msg_RequestTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File template &quot;{0}&quot; is not exist..
        /// </summary>
        public static string Common_Msg_TemplateFileNotExist {
            get {
                return ResourceManager.GetString("Common_Msg_TemplateFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t access this function. Please contact with your manager for more informations..
        /// </summary>
        public static string Common_Msg_UnAuthorize {
            get {
                return ResourceManager.GetString("Common_Msg_UnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm saving this record?.
        /// </summary>
        public static string Common_Msg_UpdateConfirm {
            get {
                return ResourceManager.GetString("Common_Msg_UpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes could not be saved because the data was changed by {0} while you were editing.&lt;br/&gt;Please refresh the page to get the latest data and try again..
        /// </summary>
        public static string Common_Msg_UpdateDuplicate {
            get {
                return ResourceManager.GetString("Common_Msg_UpdateDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has not been successfully updated. Please recheck all the data..
        /// </summary>
        public static string Common_Msg_UpdateFail {
            get {
                return ResourceManager.GetString("Common_Msg_UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been successfully updated..
        /// </summary>
        public static string Common_Msg_UpdateSuccess {
            get {
                return ResourceManager.GetString("Common_Msg_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is already existed..
        /// </summary>
        public static string ERR0003 {
            get {
                return ResourceManager.GetString("ERR0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repuest timeout..
        /// </summary>
        public static string ERR0012 {
            get {
                return ResourceManager.GetString("ERR0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder name you have chosen already exists. Please try another name..
        /// </summary>
        public static string ERR0082 {
            get {
                return ResourceManager.GetString("ERR0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Please Select ---.
        /// </summary>
        public static string INF0010 {
            get {
                return ResourceManager.GetString("INF0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID or Password is incorrect. Please try again..
        /// </summary>
        public static string L0101_Msg02 {
            get {
                return ResourceManager.GetString("L0101_Msg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has not been changed for the past 90 days. Please change your password now..
        /// </summary>
        public static string L0101_Msg03 {
            get {
                return ResourceManager.GetString("L0101_Msg03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password and new password must not be the same..
        /// </summary>
        public static string L0102_Msg02 {
            get {
                return ResourceManager.GetString("L0102_Msg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password does not match. Please try again..
        /// </summary>
        public static string L0102_Msg03 {
            get {
                return ResourceManager.GetString("L0102_Msg03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password &amp; Retype password do not match. Please try again..
        /// </summary>
        public static string L0102_Msg04 {
            get {
                return ResourceManager.GetString("L0102_Msg04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters. Please try again..
        /// </summary>
        public static string L0102_Msg05 {
            get {
                return ResourceManager.GetString("L0102_Msg05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been successfully changed!.
        /// </summary>
        public static string L0102_Msg06 {
            get {
                return ResourceManager.GetString("L0102_Msg06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select User Role..
        /// </summary>
        public static string M0110_Msg01 {
            get {
                return ResourceManager.GetString("M0110_Msg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Role is existed..
        /// </summary>
        public static string M0110_Msg02 {
            get {
                return ResourceManager.GetString("M0110_Msg02", resourceCulture);
            }
        }
    }
}
