//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBHelpDataContext : DbContext
    {
        public DBHelpDataContext()
            : base("name=DBHelpDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_ASSESSMENT_YEAR> M_ASSESSMENT_YEAR { get; set; }
        public virtual DbSet<M_BONUS_SALARY_BASEUP> M_BONUS_SALARY_BASEUP { get; set; }
        public virtual DbSet<M_BONUS_SALARY_PI> M_BONUS_SALARY_PI { get; set; }
        public virtual DbSet<M_BONUS_SALARY_PROMOTION> M_BONUS_SALARY_PROMOTION { get; set; }
        public virtual DbSet<M_BONUS_SALARY_SA> M_BONUS_SALARY_SA { get; set; }
        public virtual DbSet<M_COMPANY> M_COMPANY { get; set; }
        public virtual DbSet<M_COUNTRY> M_COUNTRY { get; set; }
        public virtual DbSet<M_CURRENCY> M_CURRENCY { get; set; }
        public virtual DbSet<M_DIVISION> M_DIVISION { get; set; }
        public virtual DbSet<M_EDUCATION_QUALIFICATION> M_EDUCATION_QUALIFICATION { get; set; }
        public virtual DbSet<M_EVALUATION_RATIO> M_EVALUATION_RATIO { get; set; }
        public virtual DbSet<M_GROUP> M_GROUP { get; set; }
        public virtual DbSet<M_MENU> M_MENU { get; set; }
        public virtual DbSet<M_ORGCHART> M_ORGCHART { get; set; }
        public virtual DbSet<M_ORIGIN> M_ORIGIN { get; set; }
        public virtual DbSet<M_PERSON> M_PERSON { get; set; }
        public virtual DbSet<M_QUESTION> M_QUESTION { get; set; }
        public virtual DbSet<M_QUESTION_CATEGORY> M_QUESTION_CATEGORY { get; set; }
        public virtual DbSet<M_QUESTION_LEVEL> M_QUESTION_LEVEL { get; set; }
        public virtual DbSet<M_QUESTION_TYPE> M_QUESTION_TYPE { get; set; }
        public virtual DbSet<M_ROLE> M_ROLE { get; set; }
        public virtual DbSet<M_SECTION> M_SECTION { get; set; }
        public virtual DbSet<M_STAFF> M_STAFF { get; set; }
        public virtual DbSet<M_STAFF_BAND_SALARY> M_STAFF_BAND_SALARY { get; set; }
        public virtual DbSet<M_STAFF_JOBTITLE> M_STAFF_JOBTITLE { get; set; }
        public virtual DbSet<M_STATE_PROVINCE> M_STATE_PROVINCE { get; set; }
        public virtual DbSet<MSG_ATTACHMENT> MSG_ATTACHMENT { get; set; }
        public virtual DbSet<MSG_FOLDER> MSG_FOLDER { get; set; }
        public virtual DbSet<MSG_GROUPS> MSG_GROUPS { get; set; }
        public virtual DbSet<MSG_MESAGES_USERS> MSG_MESAGES_USERS { get; set; }
        public virtual DbSet<MSG_MESSAGE> MSG_MESSAGE { get; set; }
        public virtual DbSet<MSG_SUBJECT> MSG_SUBJECT { get; set; }
        public virtual DbSet<MSG_SUBJECT_PARTICIPANT> MSG_SUBJECT_PARTICIPANT { get; set; }
        public virtual DbSet<MSG_USERS_CONTACTS> MSG_USERS_CONTACTS { get; set; }
        public virtual DbSet<MSG_USERS_IN_GROUPS> MSG_USERS_IN_GROUPS { get; set; }
        public virtual DbSet<T_ASSESSMENT_GOAL> T_ASSESSMENT_GOAL { get; set; }
        public virtual DbSet<T_BAND_PROMOTION> T_BAND_PROMOTION { get; set; }
        public virtual DbSet<T_BONUS_CALCULATION> T_BONUS_CALCULATION { get; set; }
        public virtual DbSet<T_BONUS_SALARY_PASSCODE> T_BONUS_SALARY_PASSCODE { get; set; }
        public virtual DbSet<T_EVALUATION> T_EVALUATION { get; set; }
        public virtual DbSet<T_FILETRACKING> T_FILETRACKING { get; set; }
        public virtual DbSet<T_LOG> T_LOG { get; set; }
        public virtual DbSet<T_ROLE_MENU> T_ROLE_MENU { get; set; }
        public virtual DbSet<T_SALARY_CALCULATION> T_SALARY_CALCULATION { get; set; }
        public virtual DbSet<T_SALARY_CALCULATION_FINAL> T_SALARY_CALCULATION_FINAL { get; set; }
        public virtual DbSet<T_STAFF_CONTACT> T_STAFF_CONTACT { get; set; }
        public virtual DbSet<T_STAFF_EDUCATION> T_STAFF_EDUCATION { get; set; }
        public virtual DbSet<T_STAFF_EMPLOYMENT_HISTORY> T_STAFF_EMPLOYMENT_HISTORY { get; set; }
        public virtual DbSet<V_CATEGORY> V_CATEGORY { get; set; }
        public virtual DbSet<V_EXTENSION_ATTRIBUTE> V_EXTENSION_ATTRIBUTE { get; set; }
        public virtual DbSet<V_PRODUCT> V_PRODUCT { get; set; }
    }
}
