//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BONUS_SALARY_SA
    {
        public string COMPANY_CD { get; set; }
        public int ASSESSMENT_YEAR { get; set; }
        public decimal CURRENT_AVG_AMOUNT { get; set; }
        public decimal CURRENT_AVG_PERCENT { get; set; }
        public decimal INCREMENT_AVG_AMOUNT { get; set; }
        public decimal INCREMENT_AVG_PERCENT { get; set; }
        public decimal NEW_AMOUNT_AVG { get; set; }
        public decimal NEW_AMOUNT_PERCENT { get; set; }
        public decimal BAND_B3_NOPROMO_IIB_FIX { get; set; }
        public decimal BAND_B2_NOPROMO_IIC_FIX { get; set; }
        public decimal BAND_B2_I_IIC_FIX { get; set; }
        public decimal BAND_B1_IIC_IIB_FIX { get; set; }
        public decimal BAND_B1_IIA_IIIC_FIX { get; set; }
        public decimal BAND_A2_NOPROMO_IIA_FIX { get; set; }
        public decimal BAND_B3_NOPROMO_IIB_PERCENT { get; set; }
        public decimal BAND_B2_NOPROMO_IIC_PERCENT { get; set; }
        public decimal BAND_B2_I_IIC_PERCENT { get; set; }
        public decimal BAND_B1_IIC_IIB_PERCENT { get; set; }
        public decimal BAND_B1_IIA_IIIC_PERCENT { get; set; }
        public decimal BAND_A2_NOPROMO_IIA_PERCENT { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    }
}
