//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BONUS_SALARY_PI
    {
        public string COMPANY_CD { get; set; }
        public int ASSESSMENT_YEAR { get; set; }
        public decimal AVG_RATIO_SALARY { get; set; }
        public decimal AVG_RATIO_BONUS_MONTH { get; set; }
        public decimal BAND_C1_VARIATION_SALARY { get; set; }
        public decimal BAND_B3_VARIATION_SALARY { get; set; }
        public decimal BAND_B2_VARIATION_SALARY { get; set; }
        public decimal BAND_B1_VARIATION_SALARY { get; set; }
        public decimal BAND_A2_VARIATION_SALARY { get; set; }
        public decimal BAND_A1_VARIATION_SALARY { get; set; }
        public decimal BAND_C1_VARIATION_BONUS { get; set; }
        public decimal BAND_B3_VARIATION_BONUS { get; set; }
        public decimal BAND_B2_VARIATION_BONUS { get; set; }
        public decimal BAND_B1_VARIATION_BONUS { get; set; }
        public decimal BAND_A2_VARIATION_BONUS { get; set; }
        public decimal BAND_A1_VARIATION_BONUS { get; set; }
        public decimal BAND_C1_FINALRATIO_SALARY { get; set; }
        public decimal BAND_B3_FINALRATIO_SALARY { get; set; }
        public decimal BAND_B2_FINALRATIO_SALARY { get; set; }
        public decimal BAND_B1_FINALRATIO_SALARY { get; set; }
        public decimal BAND_A2_FINALRATIO_SALARY { get; set; }
        public decimal BAND_A1_FINALRATIO_SALARY { get; set; }
        public decimal BAND_C1_FINALRATIO_BONUS { get; set; }
        public decimal BAND_B3_FINALRATIO_BONUS { get; set; }
        public decimal BAND_B2_FINALRATIO_BONUS { get; set; }
        public decimal BAND_B1_FINALRATIO_BONUS { get; set; }
        public decimal BAND_A2_FINALRATIO_BONUS { get; set; }
        public decimal BAND_A1_FINALRATIO_BONUS { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    }
}
