//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_COMPANY
    {
        public string COMPANY_CD { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<int> GM_STAFF_CD { get; set; }
        public string COMPANY_ADDR1 { get; set; }
        public string COMPANY_ADDR2 { get; set; }
        public string COMPANY_PHONE { get; set; }
        public string COMPANY_FAX { get; set; }
        public string COUNTRY_CD { get; set; }
        public string CURRENCY_CD { get; set; }
        public Nullable<int> CURRENCY_UNIT { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
        public Nullable<int> LAST_STAFF_ID { get; set; }
    
        public virtual M_COUNTRY M_COUNTRY { get; set; }
        public virtual M_CURRENCY M_CURRENCY { get; set; }
    }
}
