//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PERSON
    {
        public string COMPANY_CD { get; set; }
        public int PERSON_CD { get; set; }
        public int STAFF_ID { get; set; }
        public int ROLE_CD { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string PASSWORD_SALT { get; set; }
        public Nullable<System.DateTime> LAST_CHANGE_PWD_DATE { get; set; }
        public Nullable<bool> RESET_FLG { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    
        public virtual M_ROLE M_ROLE { get; set; }
        public virtual M_STAFF M_STAFF { get; set; }
    }
}
