//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_STATE_PROVINCE
    {
        public int ID { get; set; }
        public string COUNTRY_CD { get; set; }
        public string NAME { get; set; }
        public string ABBREVIATION { get; set; }
        public bool DEL_FLG { get; set; }
        public int DISPLAY_ORDER { get; set; }
    
        public virtual M_COUNTRY M_COUNTRY { get; set; }
    }
}
