//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG_MESAGES_USERS
    {
        public decimal MESSAGE_ID { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> READ_DATE { get; set; }
        public Nullable<byte> IS_READ { get; set; }
    
        public virtual MSG_MESSAGE MSG_MESSAGE { get; set; }
    }
}
