//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG_USERS_IN_GROUPS
    {
        public string GROUP_CD { get; set; }
        public int USER_ID { get; set; }
        public int FRIEND_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual MSG_GROUPS MSG_GROUPS { get; set; }
        public virtual MSG_GROUPS MSG_GROUPS1 { get; set; }
        public virtual MSG_USERS_CONTACTS MSG_USERS_CONTACTS { get; set; }
    }
}
