//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vap.EAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public V_PRODUCT()
        {
            this.V_EXTENSION_ATTRIBUTE = new HashSet<V_EXTENSION_ATTRIBUTE>();
        }
    
        public string PRODUCT_CD { get; set; }
        public string CATEGORY_CD { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_KEYWORD { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public Nullable<int> SORT_ORDER { get; set; }
        public short PRODUCT_STATUS_CD { get; set; }
        public bool DISPLAY_FLG { get; set; }
        public bool DEL_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_PERSON_CD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSON_CD { get; set; }
    
        public virtual V_CATEGORY V_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_EXTENSION_ATTRIBUTE> V_EXTENSION_ATTRIBUTE { get; set; }
    }
}
